# Generated by Django 3.2.5 on 2021-10-12 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=555)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adsdsd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=555)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asdsd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
