# Generated by Django 3.2.3 on 2022-04-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_auto_20211223_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
