# Generated by Django 3.2.5 on 2021-10-12 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_auto_20211013_0252'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='seminar_ticket_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending BOARD'), ('Failed', 'Failed'), ('Processing', 'Processing'), ('Refunded', 'Refunded'), ('Done', 'Done')], default='UN', max_length=11)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminar_lecsdture', to=settings.AUTH_USER_MODEL)),
                ('seminar_lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addsd', to='main.seminar')),
            ],
        ),
        migrations.CreateModel(
            name='lecture_ticket_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending BOARD'), ('Failed', 'Failed'), ('Processing', 'Processing'), ('Refunded', 'Refunded'), ('Done', 'Done')], default='UN', max_length=11)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminarsd_lecture', to=settings.AUTH_USER_MODEL)),
                ('seminar_lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addsdsd', to='main.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='event_ticket_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending BOARD'), ('Failed', 'Failed'), ('Processing', 'Processing'), ('Refunded', 'Refunded'), ('Done', 'Done')], default='UN', max_length=11)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addsdgffgvgb', to='main.event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_ticket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
