# Generated by Django 3.2.5 on 2021-10-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_event_ticket_booking_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_ticket_booking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Failed', 'Failed'), ('Processing', 'Processing'), ('Refunded', 'Refunded'), ('Done', 'Done')], default='UN', max_length=11),
        ),
        migrations.AlterField(
            model_name='lecture_ticket_booking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Failed', 'Failed'), ('Processing', 'Processing'), ('Refunded', 'Refunded'), ('Done', 'Done')], default='UN', max_length=11),
        ),
        migrations.AlterField(
            model_name='seminar_ticket_booking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Failed', 'Failed'), ('Processing', 'Processing'), ('Refunded', 'Refunded'), ('Done', 'Done')], default='UN', max_length=11),
        ),
    ]
