# Generated by Django 3.0.8 on 2022-03-23 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20220323_2041'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0005_auto_20211223_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('any_suggestions', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edfvsdefcesf', to='main.Event')),
                ('feeback_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efesfszsfwe', to='main.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wdedcsscd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
