# Generated by Django 3.0.8 on 2022-03-25 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0043_feedback_questions'),
        ('booking', '0009_auto_20220324_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edfvsdefcesf', to='main.Event')),
                ('feeback_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efesfszsfwe', to='main.feedback_questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wdedcsscd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
