# Generated by Django 3.0.8 on 2022-04-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20220325_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_ticket_booking',
            name='razorpay_order_id',
            field=models.CharField(default='sdsdsd', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_ticket_booking',
            name='razorpay_payment_id',
            field=models.CharField(default='dsdsd', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_ticket_booking',
            name='razorpay_signature',
            field=models.CharField(default='sdsdsd', max_length=500),
            preserve_default=False,
        ),
    ]
