# Generated by Django 3.0.8 on 2022-06-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20220426_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_ticket_booking',
            name='payment_status',
            field=models.CharField(choices=[(1, 'Pending'), (2, 'Failed'), (3, 'Processing'), (4, 'Refunded'), (5, 'Done')], default='UN', max_length=11),
        ),
        migrations.AlterField(
            model_name='lecture_ticket_booking',
            name='payment_status',
            field=models.CharField(choices=[(1, 'Pending'), (2, 'Failed'), (3, 'Processing'), (4, 'Refunded'), (5, 'Done')], default='UN', max_length=11),
        ),
        migrations.AlterField(
            model_name='seminar_ticket_booking',
            name='payment_status',
            field=models.CharField(choices=[(1, 'Pending'), (2, 'Failed'), (3, 'Processing'), (4, 'Refunded'), (5, 'Done')], default='UN', max_length=11),
        ),
    ]
