# Generated by Django 3.2.5 on 2021-10-12 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_description', models.CharField(max_length=555)),
                ('description', models.CharField(max_length=555)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addsdfdfd', to=settings.AUTH_USER_MODEL)),
                ('event_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addxfdfsddsa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_description', models.CharField(max_length=555)),
                ('description', models.CharField(max_length=555)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asffddfdfd', to=settings.AUTH_USER_MODEL)),
                ('event_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addddsa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('description', models.CharField(max_length=555)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adwed', to=settings.AUTH_USER_MODEL)),
                ('event_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addsdsw', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
