# Generated by Django 3.2.5 on 2021-10-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_seminar_entry_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='entry_for',
            field=models.CharField(choices=[('Single', 'Single'), ('Group', 'Group'), ('Single or Group', 'Single or Group')], default='Single', max_length=255),
        ),
    ]
