# Generated by Django 3.2.5 on 2021-10-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211013_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lecturer_name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
