# Generated by Django 3.2.5 on 2021-10-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_event_lecturer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='guest_description',
            new_name='lecturer_description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lecturer_name',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='guest_name',
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecturer_name',
            field=models.CharField(default='abc', max_length=255),
        ),
    ]
