# Generated by Django 3.2.5 on 2021-10-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211013_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
