# Generated by Django 3.2.5 on 2021-10-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_event_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='min_participants',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
