# Generated by Django 3.2.5 on 2021-10-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_event_min_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Guidance',
            field=models.CharField(default='pratik', max_length=255),
            preserve_default=False,
        ),
    ]
