# Generated by Django 3.2.5 on 2021-10-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_event_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_schedule',
            name='number_of_days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
