# Generated by Django 3.2.5 on 2021-10-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211024_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='entry_for',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
