# Generated by Django 3.2.5 on 2021-10-29 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_event_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_schedule',
            name='date_time',
        ),
        migrations.AddField(
            model_name='event_schedule',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event_schedule',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
