# Generated by Django 3.2.5 on 2021-10-30 09:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20211030_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('event_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsddsd', to='main.event_schedule')),
            ],
        ),
    ]
