# Generated by Django 3.2.5 on 2021-10-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_event_rounds_event_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day_details',
            old_name='event_schedule',
            new_name='day',
        ),
        migrations.AlterField(
            model_name='day_details',
            name='description',
            field=models.CharField(max_length=555),
        ),
    ]
