# Generated by Django 3.2.5 on 2021-11-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20211031_1651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Day_details',
            new_name='Day_Schedule',
        ),
    ]
