# Generated by Django 3.2.5 on 2021-11-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_day_details_day_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='sdsd/sdsd', upload_to='media/'),
            preserve_default=False,
        ),
    ]
