# Generated by Django 3.2.5 on 2021-11-13 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_schedule',
            name='description',
            field=models.CharField(max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='day_schedule',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='day_schedule',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='day_schedule',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event_days',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event_days',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='event_days',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='event_days',
            name='sub_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event_days',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
