# Generated by Django 3.2.5 on 2021-11-20 10:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20211120_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar_Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('sub_title', models.CharField(max_length=255, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sd', to='main.seminar')),
            ],
        ),
        migrations.CreateModel(
            name='Seminar_Day_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('description', models.CharField(max_length=555, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sd', to='main.seminar_days')),
            ],
        ),
    ]
