# Generated by Django 3.2.5 on 2021-11-24 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20211125_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day_schedule',
            name='day',
        ),
        migrations.RemoveField(
            model_name='day_schedule',
            name='description',
        ),
        migrations.RemoveField(
            model_name='day_schedule',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='day_schedule',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='day_schedule',
            name='title',
        ),
        migrations.AddField(
            model_name='day_schedule',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sdsdsadc', to='main.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day_schedule',
            name='first_price_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='day_schedule',
            name='second_price_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='day_schedule',
            name='third_price_money',
            field=models.IntegerField(default=0),
        ),
    ]
