# Generated by Django 3.2.5 on 2021-11-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20211125_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='first_price_money',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='second_price_money',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='third_price_money',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event_prices',
            name='first_price_money',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event_prices',
            name='second_price_money',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event_prices',
            name='third_price_money',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='price',
            field=models.IntegerField(),
        ),
    ]
