# Generated by Django 3.2.5 on 2021-12-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20211125_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar',
            old_name='number_of_days',
            new_name='event_cordinator',
        ),
        migrations.RenameField(
            model_name='seminar',
            old_name='guidance',
            new_name='hod',
        ),
    ]
