# Generated by Django 3.2.5 on 2021-12-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20211210_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_leader',
            new_name='event_cordinator',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='guidance',
            new_name='hod',
        ),
        migrations.RenameField(
            model_name='seminar',
            old_name='hod',
            new_name='guidance',
        ),
        migrations.RenameField(
            model_name='seminar',
            old_name='event_cordinator',
            new_name='number_of_days',
        ),
    ]
