# Generated by Django 3.2.5 on 2021-12-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20211210_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='department',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
