# Generated by Django 3.2.5 on 2021-12-15 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0036_event_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='event_leader',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='guidance',
        ),
        migrations.AddField(
            model_name='seminar',
            name='department',
            field=models.CharField(default='asas', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminar',
            name='event_cordinator',
            field=models.CharField(default='pratik gosavi', max_length=555),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminar',
            name='hod',
            field=models.CharField(default='pratik gosavi', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminar',
            name='max_participants',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminar',
            name='min_participants',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seminar',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsd', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='description',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='number_of_days',
            field=models.IntegerField(),
        ),
    ]
