# Generated by Django 3.0.8 on 2022-01-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20211223_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_prices',
            old_name='first_price_money',
            new_name='prize',
        ),
        migrations.RemoveField(
            model_name='event_prices',
            name='second_price_money',
        ),
        migrations.RemoveField(
            model_name='event_prices',
            name='third_price_money',
        ),
        migrations.AddField(
            model_name='event_prices',
            name='rank',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], default=1, max_length=343),
            preserve_default=False,
        ),
    ]
