# Generated by Django 3.0.8 on 2022-01-27 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0039_auto_20220127_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_prices',
            name='prize',
        ),
        migrations.AddField(
            model_name='event_prices',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dfdf', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
