# Generated by Django 3.0.8 on 2022-03-23 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0041_event_prices_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdscscs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dfdefwed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='event_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addwdfwedsddsa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='teachers_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('collage', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lecturer_name', models.CharField(default='abc', max_length=255)),
                ('lecturer_description', models.CharField(max_length=555)),
                ('description', models.CharField(max_length=555)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asffddfdfd', to=settings.AUTH_USER_MODEL)),
                ('event_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addddsa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
