# Generated by Django 3.0.8 on 2022-06-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_feedback_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='min_participants',
        ),
        migrations.AddField(
            model_name='seminar',
            name='speaker',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seminar',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
